DOCS-573 Remove unsupported Viridian features
hazelcast/cloud-docs pull request #106
Opened 2023-06-25 15:46 UTC by angelasimms

The following changes are not included but will be included in forthcoming tickets:

- Changes to Viridian Dedicated product description, banners etc. 
- WAN replication (dependency on UI change).
- VPC peering for AWS (in progress as part of a separate ticket). VPC peering section has been removed until this content is ready.
- Creation of new 'Clients` section.

2023-06-26 19:27 UTC, lovanchetty requested changes

2023-06-27 09:33 UTC, angelasimms commented on docs/modules/ROOT/pages/authorize-connections.adoc
> +TIP: You must use VPC peering if your clients' IP addresses are not static or if you want to limit your cluster's exposure to the public Internet.
Checked with Atil and the endpoints I private. I will remove the misleading text.

2023-06-27 09:34 UTC, angelasimms commented on docs/modules/ROOT/pages/serverless-cluster.adoc
>  Exceeding these limits can lead to cluster failure.
@lovanchetty and @FinnLiuHZ. Attaching ticket which has all the relevant details: https://hazelcast.atlassian.net/browse/HZC-3956

2023-06-27 10:23 UTC, angelasimms commented on docs/modules/ROOT/pages/overview.adoc
>  |{hazelcast-cloud} Dedicated clusters give you fine-grained control over the hardware and resources available to your cluster. It's your responsibility to scale {hazelcast-cloud} Dedicated clusters w
Updated.

2023-06-27 10:25 UTC, angelasimms commented on docs/modules/ROOT/pages/overview.adoc
>  |xref:dedicated-cluster.adoc[{hazelcast-cloud} Dedicated] (coming soon)
Updated.

2023-06-27 14:51 UTC, lovanchetty approved these changes

2023-06-28 08:23 UTC, merged