Fix typos identified by IntelliJ
hazelcast/cloud-docs pull request #118
Opened 2023-07-26 21:02 UTC by JackPGreen

Fixes https://github.com/hazelcast/cloud-docs/issues/117

2023-07-28 14:12 UTC, angelasimms requested changes
Hi Jack, Thanks for doing this. Just a few comments. Luckily a lot of this content is legacy and will be rewritten soon.

2023-07-28 14:12 UTC, angelasimms commented on docs/modules/ROOT/pages/connect-to-cluster.adoc
> +You can open an SQL shell in your cluster and submit SQL queries directly from your web browser.
This is not correct even though IntelliJ might think so.

2023-07-28 14:12 UTC, angelasimms commented on docs/modules/ROOT/pages/create-account.adoc
> +- *Enable multifactor authentication:* Protect your account from anyone who may know your username and password. With xref:multi-factor-authentication.adoc[multifactor authentication], you'll need to
This is not incorrect, simply an editorial choice. We tend to follow Merriam Webster: https://www.merriam-webster.com/dictionary/multi-factor%20authentication

2023-07-28 14:12 UTC, angelasimms commented on docs/modules/ROOT/pages/get-started.adoc
> +An SQL prompt is displayed:
IntelliJ is incorrect I'm afraid.

2023-07-28 14:12 UTC, angelasimms commented on docs/modules/ROOT/pages/get-started.adoc
> +Now that you have some data in your cluster, you can query it using SQL. If you're using the CLI, enter the following  queries in the SQL prompt. If you're using a client library, enter the following
IntelliJ is incorrect again. Can you leave as is.

2023-07-28 14:12 UTC, angelasimms commented on docs/modules/ROOT/pages/multi-factor-authentication.adoc
> += Multifactor Authentication
As per earlier comment. Can you leave as is?

2023-07-28 14:12 UTC, angelasimms commented on docs/modules/ROOT/pages/multi-factor-authentication.adoc
> +:description: Multifactor authentication (MFA) makes your account more secure by adding an extra step to the sign-in process. Instead of just entering a password, MFA allows you to use a trusted devi
As per earlier comment, can you leave as is.

2023-08-11 13:11 UTC, JackPGreen commented
@angelasimms are you able to have a look over the requested changes, please?

2023-08-11 13:31 UTC, angelasimms requested changes
Just a couple of updates.

2023-08-11 13:31 UTC, angelasimms commented on docs/modules/ROOT/pages/create-account.adoc
> +- *Enable multi-factor authentication:* Protect your account from anyone who may know your username and password. With xref:multi-factor-authentication.adoc[multifactor authentication], you'll need t
```suggestion
- *Enable multi-factor authentication:* Protect your account from anyone who may know your username and password. With xref:multi-factor-authentication.adoc[multi-factor authentication], you'll need to provide a unique code that's generated on your device as well as your username and password to sign in.
```
Makes consistent with another change below.

2023-08-11 13:31 UTC, angelasimms commented on docs/modules/ROOT/pages/multi-factor-authentication.adoc
> += Multi-factor Authentication
```suggestion
= Multi-Factor Authentication
```
For title case, this is correct.

2023-08-11 13:34 UTC, angelasimms approved these changes

2023-08-11 13:35 UTC, merged