HZC-960: C++ Sample Client
hazelcast/cloud-docs pull request #26
Opened 2021-05-28 08:02 UTC by yunussandikci

Hi, this pull request adds C++ Client documentation.

2021-05-31 08:21 UTC, uddr approved these changes
lgtm

2021-05-31 11:46 UTC, galibey approved these changes

2021-06-02 19:59 UTC, nosan approved these changes

2021-06-04 09:05 UTC, JakeSCahill reviewed
Looks good. Just some general comments and suggestions.

2021-06-04 09:05 UTC, JakeSCahill commented on docs/modules/ROOT/pages/cpp-client.adoc
> +<6> Then, we check add a value to our map, and get it to let the code throw an exception if the value is not correct.
```suggestion
<6> Then, we add an entry to our map and read it back to check that everything is working.
```

2021-06-04 09:05 UTC, JakeSCahill commented on docs/modules/ROOT/pages/cpp-client.adoc
> +<3> We set discovery token of our cluster.
```suggestion
<3> Then, we set our cluster's discovery token. 
```

2021-06-04 09:05 UTC, JakeSCahill commented on docs/modules/ROOT/pages/cpp-client.adoc
> +This discovery token will be used by client in order to discover cluster members.
```suggestion
The client will use this discovery token to discover cluster members.
```

2021-06-04 09:05 UTC, JakeSCahill commented on docs/modules/ROOT/pages/cpp-client.adoc
> +<4> We set our certificate file, key file and password in order establish a secure connection with our Cluster..
```suggestion
<4> To establish a secure connection to our cluster, we set our certificate file, key file and password.
```

2021-06-04 09:05 UTC, JakeSCahill commented on docs/modules/ROOT/pages/cpp-client.adoc
> +<5> We create the client with our `config`.
```suggestion
<5> We create the client, using our `config` object.
```

2021-06-04 09:05 UTC, JakeSCahill commented on docs/modules/ROOT/pages/cpp-client.adoc
> +<7> Then, we check add a value to our map, and get it to let the code throw an exception if the value is not correct.
```suggestion
<7> Then, we add an entry to our map and read it back to check that everything is working.
```

2021-06-08 14:08 UTC, yunussandikci commented on docs/modules/ROOT/pages/cpp-client.adoc
> +<5> We create the client with our `config`.
Done, thanks!

2021-06-08 14:08 UTC, yunussandikci commented on docs/modules/ROOT/pages/cpp-client.adoc
> +<7> Then, we check add a value to our map, and get it to let the code throw an exception if the value is not correct.
Done, thanks!

2021-06-08 14:09 UTC, yunussandikci commented on docs/modules/ROOT/pages/cpp-client.adoc
> +<4> We set our certificate file, key file and password in order establish a secure connection with our Cluster..
Done, thanks!

2021-06-08 14:11 UTC, yunussandikci commented on docs/modules/ROOT/pages/cpp-client.adoc
> +This discovery token will be used by client in order to discover cluster members.
Done, thanks!

2021-06-10 18:47 UTC, yunussandikci commented on docs/modules/ROOT/pages/cpp-client.adoc
> +<3> We set discovery token of our cluster.
Done, thanks!

2021-06-10 18:48 UTC, yunussandikci commented on docs/modules/ROOT/pages/cpp-client.adoc
> +<6> Then, we check add a value to our map, and get it to let the code throw an exception if the value is not correct.
Done, thanks!

2021-06-10 18:48 UTC, yunussandikci commented on docs/modules/ROOT/pages/cpp-client.adoc
> +This discovery token will be used by client in order to discover cluster members.
Done, thanks!

2021-06-10 18:49 UTC, yunussandikci commented on docs/modules/ROOT/pages/cpp-client.adoc
> +<4> Now, we create the client with `config`.
Done, thanks!

2021-06-10 18:51 UTC, yunussandikci commented on docs/modules/ROOT/pages/cpp-client.adoc
> +** Location of the compiled binary may change according to configuration and system defaults.
Yes I tried this on both macOS and Windows and compiled binary was in different direction. It applies only to Windows users.

2021-06-10 18:52 UTC, yunussandikci commented on docs/modules/ROOT/pages/cpp-client.adoc
> +** If your target triple doesn't match with operation system, you may need to install Client with providing target suffix. For example: `vcpkg install "hazelcast-cpp-client[openssl]:x64-windows"`
Typo, it should be `target triplet` You can check what is it from here: https://wiki.osdev.org/Target_Triplet

2021-06-15 08:43 UTC, JakeSCahill commented on docs/modules/ROOT/pages/cpp-client.adoc
> +** If your target triple doesn't match with operation system, you may need to install Client with providing target suffix. For example: `vcpkg install "hazelcast-cpp-client[openssl]:x64-windows"`
Ah cool, thanks 😄  In that case we can say
```suggestion
** If the link:https://wiki.osdev.org/Target_Triplet[target triplet] doesn't match your operation system, you may need to provide a target suffix to the `install` command. For example: `vcpkg install "hazelcast-cpp-client[openssl]:x64-windows"`
```

2021-06-15 08:47 UTC, JakeSCahill requested changes
Just one final suggestion regarding the typo in `target triple`.

2021-06-24 08:16 UTC, JakeSCahill approved these changes
Thanks 😄

2021-06-24 08:31 UTC, yunussandikci commented
Thanks @JakeSCahill I will merge it when we need it. (Release 3.0)

2021-08-05 13:42 UTC, JakeSCahill approved these changes

2021-08-05 13:43 UTC, merged